name: CI/CD GitHub Pages

on:
  push:
    branches:
      - '**'  # Toutes les branches

jobs:
  deploy_or_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "actor=${{ github.actor }}" >> $GITHUB_ENV
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy or Create PR
        run: |
          if [ "$actor" = "imani08" ] && [ "$branch" = "main" ]; then
            echo "C'est toi ! Déploiement vers GitHub Pages..."
            npm install
            npm run build   # ou autre commande si nécessaire

            # Déploiement GitHub Pages
            npx gh-pages -d build
          else
            echo "Création d'une branche et d'une PR pour $actor"
            NEW_BRANCH="auto/${actor}-$(date +%s)"
            git checkout -b $NEW_BRANCH
            git push origin $NEW_BRANCH

            gh pr create --title "Proposition de $actor" \
                         --body "PR automatique pour $actor vers main." \
                         --base main \
                         --head $NEW_BRANCH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
